name: Send Webhook

on:
  push:
    branches:
      - main  # mainブランチにpushされた時にトリガーされる

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send Discord Webhook
      run: |
        curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
        -H "Content-Type: application/json" \
        -d '{
          "embeds": [
            {
              "title": "🎁 新しい寄付がありました！",
              "color": 5763719,
              "fields": [
                {"name": "🆔 Minecraft ID", "value": "${{ secrets.MC_ID }}", "inline": true},
                {"name": "💬 Discord ID", "value": "${{ secrets.DISCORD_ID }}", "inline": true},
                {"name": "🎮 エディション", "value": "${{ secrets.VERSION }}", "inline": true},
                {"name": "💵 寄付プラン", "value": "${{ secrets.PLAN_NAME }}", "inline": true}
              ],
              "footer": {
                "text": "🎉 ご支援ありがとうございます！"
              },
              "timestamp": "'$(date --utc +%FT%TZ)'"
            }
          ]
        }'
